baseURL = "https://tell-me-something.pages.dev/"
languageCode = "en"
title = "Tell Me Something"
theme = "PaperMod"

[params]
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = false

  [params.homeInfoParams]
    Title = "Tell Me Something 👁️"
    Content = "Receive anonymous messages from anyone. Nobody will know it was them!"

  [[params.homeInfoParams.links]]
    name = "Create my account 🚀"
    url = "/app/"

[menu]
  [[menu.main]]
    name = "Sign Up"
    url = "/app/"
    weight = 1
  [[menu.main]]
    name = "Privacy Policy"
    url = "/privacy.html"
    weight = 2
  [[menu.main]]
    name = "Terms"
    url = "/terms.html"
    weight = 3